baseURL = "https://daniel1noble.github.io/Developmental_Temperature_Database/"
languageCode = "en-us"
title = "Welcome to the Reptile Developmental Temperature Database!"
theme = "beautifulhugo"

[[menu.main]]
    name = "About"
    url  = "about"
    weight = 5

[[menu.main]]
    name = "Blog"
    url  = "blog"
    weight = 5

[[menu.main]]
    name = "Database"
    url  = "database"
    weight = 10